cost_center_num = {'General':'G',
                           'Valve Contract':'V',
                           'Pump Contract':'P',
                           'Process diagnostics':'PD',
                           'Operations Department':'O',
                           'City shop':'C',
                           'Karabatan shop':'K',
                           'D-Island shop':'D'}

names = ['Aizada Abtay',
                 'Anuarbek Muhammed',
                 'Akhmediyar Salykov',
                 'Adrian Owen',
                 'Aizada Muratova',
                 'Andrew Davidson',
                 'Berik Gibbatulin',
                 'Dias Kuraishov',
                 'Lyailya Sarbayeva',
                 'Nurlan Zhunussov',
                 'John Carter',
                 'Akmaral Izteleuova',
                 'Adilet Kumarov',
                 'Nurgul Mukanova',
                 'Salamat Maukenov',
                 'Tarasbaev Azamat',
                 'Sergey Mazur',
                 'Karlygash Lepessova',
                 'Nurgul Zhubanova',
                 'Aimira Dzhumagalieva',
                 'Shynar Ramazanova']

types = {'Workshop equipment | Оборудование для цеха':'001',
         'Workshop tools | Инструменты для цеха':'002',
         'Workshop consumables | Расходные материалы для цеха':'003',
         'PPE, Safety equipment |СИЗ и оборудование по ТБ':'004',
         'Office equipment and furniture | Офисное оборудование и мебель':'005',
         'Office consumables and stationary | Расходные материалы и канцелярские товары':'O06',
         'Purchase of services for workshop | Услуги для цеха':'007',
         'Car maintenance and car consumables | Обслуживание автомобилей и расходные материалы к автомобилям':'008',
         'Office maintenance (household expenses, tea, cofffee) | Обеспечение офиса':'009',
         'Repair of fixed assets | Ремонт основных средств':'010',
         'Third-party services | Услуги третьей стороны':'011',
         'Trainings | Тренинги':'012',
         'IT software applications, licenses, etc':'013'
         }